### ISSUE TITLE
debugger watch / tooltips are overly verbose / not tuned for Rust in general 

### ISSUE THREAD

**Issue by parthopdas** [kitamstudios/rust-analyzer.vs#1] opened 2023-01-31 18:20 UTC
need to author a nativis file https://learn.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2022 the first draft should be pretty easy.

**Comment by tim-weis** [comment] 2023-04-02 18:13
Forgive my ignorance here. I was under the impression that [RFC 3191: `debugger_visualizer`](https://rust-lang.github.io/rfcs/3191-debugger-visualizer.html) has landed, with natvis visualizers deployed for (at least some of) the Standard Library types.

Running the following

*src/main.rs*

```rust
fn main() {
    let v = vec![42; 3];
    println!("{:#?}", &v);
}
```

*Cargo.toml*

```toml
[package]
name = "natvis-test"
version = "0.0.0"
edition = "2021"
```

gets me to this in Visual Studio's debugger:

![image](https://user-images.githubusercontent.com/23303506/229370492-261f780e-c7c3-4a87-a90b-8892966680b8.png)

Hovering over `v`, or adding a *Watch* yields the same output, so everything appears to work as intended.

Could you share a use case where things don't work as expected? I'll gladly have a look, since debugging support is (IMHO) the *true* killer feature of this Visual Studio Extension.

**Comment by parthopdas** [comment] 2023-04-03 01:40
@tim-weis thank you for responding : )

i filed this based on a comment and then my investigations show the same results. however when i sucked in the nativis from rust-lang/rust they did not fix. so i left this issue as a tracking issue

![image](https://user-images.githubusercontent.com/2140460/229392901-5f122e1b-39b9-4bb6-964d-7700a9f72a03.png)

it will be very nice if you can take a look.

**Comment by tim-weis** [comment] 2023-04-03 19:17
Thanks for the details, @parthopdas!

I can confirm that `Option`'s aren't displayed in an ideal way (the same is true for `Result`'s).

Either one is an `enum`, and enums receive their debug visualizer support from [intrinsic.natvis](https://github.com/rust-lang/rust/blob/master/src/etc/natvis/intrinsic.natvis), straight out of the Rust compiler[^1]. Things get rather tricky from here:

For one, the visualizers should *really* be written by the developers that own the [library](https://github.com/rust-lang/rust/tree/master/library) code. They are the ones that control the innards of the types, and can arrange to keep the visualizers in lock-step with the implementation.

And then there's the technical challenge in convincing the debug engine to favor an (external) .natvis file over the PDB-provided visualizer description. In countless iterations over the .natvis' `<Type Name="anything I could think of">` I didn't manage to, though I'm not nearly even an amateur in natvis infrastructure. I'll be all ears in case someone knows how to deterministically control the selection of visualizers (or knows where to find a description of the selection algorithm).

From a client's perspective, it would be great if debug visualizers lived up to what we have grown to expect. I'm not positive that this is something this extension can provide. Dropping a few unsolicited pings to folks that have contributed to Rust's natvis support, to validate my assumptions (@wesleywiser @sivadeilra @ridwanabdillahi).

---

Leaving a few notes, just because I know I *will* forget:

* Custom .natvis files can be placed under `%USERPROFILE%\Documents\Visual Studio 2022\Visualizers` for testing (see [Natvis file locations](https://learn.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2022#BKMK_natvis_location))
* Make sure to turn on [natvis diagnostics](https://learn.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2022#BKMK_Diagnosing_Natvis_errors) by going to **Tools** > **Options** > **Debugging** > **Output Window**, and setting **Natvis diagnostic messages (C++ only)** to **Error**, **Warning**, or **Verbose**. This will produce helpful diagnostics during visualizer evaluation. The option reads **"C++ only"**, but it seems to mean **"anything native"**.

[^1]: The idea here is that debug visualizers are the responsibility of the implementer of a type.

**Comment by parthopdas** [comment] 2023-04-06 19:15
thanks for the detailed investigation @tim-weis and the notes that will be helpful in the future.

i am wondering if you could file a bug in [@rust](https://github.com/rust-lang/rust) to fix this. i agree with you that the lib developer should own the nativis

**Closed** 2023-12-07 21:28 UTC
Labels: help wanted
